### ISSUE TITLE
Cannot Find an Overload for Add 

### ISSUE THREAD

**Issue by blundahl** [cyberark/epv-api-scripts#100]
I am unable to run any variations of the script for SafeManagement.ps1.  Below is the output from running -list.  

.\SafeManagement.ps1 -List -PVWAURL "https://****pvwaurl***/passwordvault"

=======================================
Starting script (v1.5)
Safe Management
Enter your User name and Password
User: ***********************
Password for user *************: ********************
Error Logging on. Error: Source:System.Management.Automation; Message: Cannot find an overload for "Add" and the argument count: "2".
Retrieving Safes...
Error retrieving safes. Error: Source:; Message: Get-Safes: There was an error retrieving the safes from the Vault.
        ->Source:System.Management.Automation; Message: Cannot bind parameter 'Headers'. Cannot convert the "" value of type "System.String" to type "System.Collections.IDictionary".
        ->Source:System.Management.Automation; Message: Cannot convert the "" value of type "System.String" to type "System.Collections.IDictionary".
Logoff Session...
Run-Logoff: Failed to logoff session
At C:\******\CyberArk\SafeManagement\SafeManagement.ps1:361 char:3
+         Throw $(New-Object System.Exception ("Run-Logoff: Failed to l ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Run-Logoff: Failed to logoff session

**Comment by AssafMiron** [comment]
Hello @blundahl ,

It seems that you have an issue creating the required Dictionary needed for the logon header
I added some error handling around that area for the next commit
But please verify that you are running a powershell version of version 3 or above and that you are not restricted with some methods.
Try running the following command and let me know what is the output:
$logonHeader =  New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
If this succeeds, please type the output of the following command:
$logonHeader.GetType()

Thanks,
Assaf

**Comment by blundahl** [comment]
@AssafMiron Thanks for your help.  Here is a screenshot of the output from those commands.
![2020-07-27_9-55-11](https://user-images.githubusercontent.com/43765339/88569632-8d1f6600-cfef-11ea-80ac-3c5c3ccefa64.png)

**Comment by AssafMiron** [comment]
Thanks, this still looks like a local powershell issue

One thing to recommend is running the script with -Debug -Verbose switches
This will give the output of all commands with more information
So if the logon process fails because of SSL issues for example we would see it and it might explain the above error

Another thing would be to run the commands of the logon manually
So these are the commands that you need to run in order to check it:

$URL_PVWAWebServices = $PVWAURL+"/WebServices"
$URL_PVWABaseAPI = $URL_PVWAWebServices+"/PIMServices.svc"
$URL_CyberArkAuthentication = $URL_PVWAWebServices+"/auth/cyberark/CyberArkAuthenticationService.svc"
$URL_Logon = $URL_CyberArkAuthentication+"/Logon"
$caption = "Safe Management"
$msg = "Enter your User name and Password"; 
$Credentials = $Host.UI.PromptForCredential($caption,$msg,"","")
$logonBody = @{ username=$Credentials.username.Replace('\',''); password=$Credentials.GetNetworkCredential().password } | ConvertTo-Json
$logonToken = Invoke-RestMethod -Method Post -Uri $URL_Logon -Body $logonBody -ContentType "application/json" -TimeoutSec 3600000
$logonHeader = $null
$logonHeader =  New-Object "System.Collections.Generic.Dictionary[[String],[String]]"		$logonHeader.Add("Authorization", $logonToken)

Let me know how that works for you

**Comment by AssafMiron** [comment]
Hello @blundahl 
Please take the recent updated script, thanks to @Jayk423 this issue should be fixed

Please reopen the issue if not fixed

Thanks,
Assaf
