### ISSUE TITLE
Is it possible to create video recording safe using rest api?

### ISSUE THREAD

**Issue by engkeen-source** [cyberark/epv-api-scripts#173]
Currently in my environment, we will create SR-{safename} for each safe. It is set in platform level. 

For example, once TESTSAFE is created, SR-TESTSAFE will be create automatically once first PSM connection for any account in this safe is trigger/launched.

Is it possible to create this SR-{safename} automatically using REST API, this SR-{safename} is different from other safe as it is a video recording safe.

**Comment by AssafMiron** [comment]
Since this is a platform level setting and currently there is no "Edit Platform" REST API - then the basic answer is no.
I recommend not creating these recording safes outside of the process of the platform as you described since, like you said, these safes are created automatically in a special way to hold recordings

If your goal is to automate the owners for these safes, then this can be achieved using the Safes-Management script here:
https://github.com/cyberark/epv-api-scripts/tree/main/Safe%20Management

Hope this helps,
Assaf

**Comment by engkeen-source** [comment]
@AssafMiron  Thanks for your swift answer, meaning create SR-{safename} must trigger a psm connection , once SR-{safename} is created then only i can automate the owner for these safes.

**Comment by AssafMiron** [comment]
Correct
