### ISSUE TITLE
Is it possible to locate account ID based on safename and object name?

### ISSUE THREAD

**Issue by engkeen-source** [cyberark/epv-api-scripts#174]
In PACLI, we are able to delete object based on only safename and object name.

However, Im looking to implement REST API to perform object deletion, with the input of safename and objectname. 

Currently what Im doing is using rest api to query all object in safename, and loop through each objectname until there is match, and return account ID, the limit of object return for safename I set to 1000. 

Is there any other better method that i can locate account ID based on safename and object name.

**Comment by AssafMiron** [comment]
Hey @engkeen-source ,

I think your approach is currently the only was since searching by object name is not supported in REST API.
I can share some functions and scripts that might help you overcome the limitations that you described
See this function to search by object name and safe name: 
https://github.com/cyberark/epv-api-scripts/blob/ae00bb6b1a18f9e0a63d246daaab0161adccf823/Account%20Onboard%20Utility/Accounts_Onboard_Utility.ps1#L880

See this script that can list all accounts across all pages (not limited by 1000 accounts):
https://github.com/cyberark/epv-api-scripts/tree/main/Get%20Accounts#get-accounts
(See the -AutoNextPage switch)

Hope this helps,
Assaf

**Comment by engkeen-source** [comment]
Thanks for your swift answer, so -AutoNextPage switch allow me to loop through more than 1000 account and find the account ID.

**Comment by engkeen-source** [comment]
This case can close. Thanks again.
