### ISSUE TITLE
Update Safe-Management to include Add-Members

### ISSUE THREAD

**Issue by evanatta** [cyberark/epv-api-scripts#175]
Sir,

Can the Safe-Management script be updated to include an "Add-Members" switch?  Customers are confused that the -Add Switch is only for adding a new Safe.  The new add members switch and point to the -add function as well.  Or update the help to state that adding members to safes can be used in same manner as when adding safes but with separate CSV File.

Use case is customers who have a separate password storage utility that they want to import into an already existing CyberArk environment.  Safes already exist so customer only wanted to add new Groups to the Safe's Members and the use the Account Onboard Utility to move the credentials over.

**Comment by AssafMiron** [comment]
Hello,

The -members switch can add members
And if you want to add or update members from a file there is the
UpdateMembers switch
Do these answer your need?

Regards,
Assaf

**Comment by jeffrechten** [comment]
Hey Assaf,
No, I do not think this addresses the issue. But I think there is an easy
temporary fix we can apply by just updating the documentation to make it
more clear how to use the script. I personally wasted many more hours than
I care to admit troubleshooting this issue before I realized that how you
run the script is the key.

When reading the doc for member management, you gravitate to this section:
https://github.com/cyberark/epv-api-scripts/tree/main/Safe%20Management#safe-members-management
From that section, it appears (as you mention) that the UpdateMembers
switch is used to add or update members from a file.

The truth is that you cannot add members using UpdateMembers switch. You
must use -Add.

In full, the process must be:
1. Run first time with -Add for safes
2. Run second time with -Add for members

Since the -Add method is overloaded and reacts based on the csv format
presented, it's not immediately obvious to the user. And, the Member
documentation leads the user to believe UpdateMembers would also add.

Thanks,
Jeff

**Comment by AssafMiron** [comment]
I see what you mean...
This really depends on the CSV that is handed to the script
By the way, you can hand in a combined CSV with the columns of safe
creation and members
Do you think adding an example CSV like that with a clarification to the
docs will help solving this problem?

Thanks,
Assaf

**Comment by jeffrechten** [comment]
Hi Assaf,
Yes, I think that would be helpful.

Thanks
Jeff
