### ISSUE TITLE
Internal server error when importing the connection component

### ISSUE THREAD

**Issue by simonyzyeh** [cyberark/epv-api-scripts#23]
Run commnad as following 
.\Import-ConnectionComponents.ps1 -PVWAURL https://PAS112/PasswordVault -ConnectionComponentZipPath "c:\source\SQL Server Mgmt Studio 2018-2.zip" -Verbose

But I always got the error message :
C:\Source\epv-api-scripts-master (1)\epv-api-scripts-master\Platforms\Import-ConnectionComponents.ps1 : Error importing the connection ID, Error: Internal Server Error
位於 Line:1 col:1
+ .\Import-ConnectionComponents.ps1 -PVWAURL https://PAS112/PasswordVau ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-ConnectionComponents.ps1

Could anyone help me ?

**Comment by AssafMiron** [comment]
@simonyzyeh when did you downloaded the code for this script?
This error was fixed for an older issue
Can you please re-download the code and try again?

**Comment by simonyzyeh** [comment]
1. My CyberArk LAB is v11.2 and run on Windows 2016 with .NET 4.6  
2.In order to make sure I have right code, **I copy the source code from Git Web and save as UTF-8 text** and change file name to "Import-CC-2.ps1"
3. Run as following 

```
PS C:\Source\epv-api-scripts-master (1)\epv-api-scripts-master\Platforms> .\Import-CC-2.ps1 -PVWAURL https://PAS112/PasswordVault -ConnectionComponentZipPath "c:\source\SQL Server Mgmt Studio 2018-2.zip"
Import Connection Component: Script Started
C:\Source\epv-api-scripts-master (1)\epv-api-scripts-master\Platforms\Import-CC-2.ps1 : Error importing the connection
ID, Error: Internal Server Error
位於 Line:1 Col:1
+ .\Import-CC-2.ps1 -PVWAURL https://PAS112/PasswordVault -ConnectionCo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CC-2.ps1

Logoff Session...
Import Connection Component: Script Ended
PS C:\Source\epv-api-scripts-master (1)\epv-api-scripts-master\Platforms>

```
4. So it is same error message.

Please advise if any
Thanks

**Comment by AssafMiron** [comment]
Hello @simonyzyeh ,

Looks like the error is from the IIS (Error 500) and not PVWA REST API

- Try looking at the IIS logs for more information
- Try using a different script from this repo, just to see if any PVWA API is working for you
- I also noted that you run the script using HTTPS and a server host name (rather than a DNS), might be related to certificate validation
- Try looking at PVWA logs, search for CyberArk.WebServices.log for REST API related errors

If nothing helps, try opening a support case

Thanks

**Comment by cybr-aaronlim** [comment]
Hi @AssafMiron ,

I am having the same issue when attempting to import the ssms18 connection componen in my lab. 
I am on V11.1 PVWA with no issues with SSL/TLS settings internally.
PS C:\ConnectionComponents> ./import-ConnectionComponents.ps1 -PVWAURL https://vhacomp01.cybrlab.local/PasswordVault -Co
nnectionComponentZipPath C:\ConnectionComponents\CC-SSMS18.zip
Import Connection Component: Script Started
C:\ConnectionComponents\Import-ConnectionComponents.ps1 : Error importing the connection ID, Error: Internal Server
Error
At line:1 char:1
+ ./import-ConnectionComponents.ps1 -PVWAURL https://vhacomp01.cybrlab.local/Passw ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-ConnectionComponents.ps1

Logoff Session...
Import Connection Component: Script Ended

Is something wrong with the script now? I copied the whole script from "Raw" 

Thanks.

**Comment by AssafMiron** [comment]
Hi @cybr-aaronlim ,
Since the error returned is 500 this means this is a server error, not an error in the script or how it sends data to the PVWA
So maybe IIS Logs or PVWA logs would reveal the issue here
I suggest also running the script with -Debug -Verbose switches to see exactly where it fails

**Comment by AssafMiron** [comment]
Hi,

One other option could be because of SSL / TLS configuration
See #25 for more information

Let us know if that work

Regards,
Assaf

**Comment by cybr-aaronlim** [comment]
HI Assaf,

Here is the output:
PS C:\ConnectionComponents> .\Import-ConnectionComponents.ps1 -PVWAURL https://vhacomp01.cybrlab.local/PasswordVault -ConnectionComponentZipPath C:\ConnectionComponents\CC-SSMS18.zip -Debug -Verbose
Import Connection Component: Script Started
VERBOSE: POST https://vhacomp01.cybrlab.local/PasswordVault/api/auth/cyberark/Logon with -1-byte payload
VERBOSE: received 182-byte response of content type application/json; charset=utf-8
VERBOSE: POST https://vhacomp01.cybrlab.local/PasswordVault/api/ConnectionComponents/Import with -1-byte payload
C:\ConnectionComponents\Import-ConnectionComponents.ps1 : Error importing the connection ID, Error: Internal Server
Error
At line:1 char:1
+ .\Import-ConnectionComponents.ps1 -PVWAURL https://vhacomp01.cybrlab.local/Passw ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-ConnectionComponents.ps1

Logoff Session...
VERBOSE: POST https://vhacomp01.cybrlab.local/PasswordVault/api/auth/Logoff with 0-byte payload
VERBOSE: received 16-byte response of content type application/json; charset=utf-8
Import Connection Component: Script Ended

From my IIS Logs:
2020-03-27 08:47:53 10.0.80.11 POST /PasswordVault/api/auth/cyberark/Logon - 443 - 10.0.80.11 Mozilla/5.0+(Windows+NT;+Windows+NT+6.3;+en-US)+WindowsPowerShell/4.0 - 200 0 0 78
2020-03-27 08:47:56 10.0.80.11 POST /PasswordVault/api/ConnectionComponents/Import - 443 - 10.0.80.11 Mozilla/5.0+(Windows+NT;+Windows+NT+6.3;+en-US)+WindowsPowerShell/4.0 - 500 0 0 109
2020-03-27 08:47:56 10.0.80.11 POST /PasswordVault/api/auth/Logoff - 443 - 10.0.80.11 Mozilla/5.0+(Windows+NT;+Windows+NT+6.3;+en-US)+WindowsPowerShell/4.0 - 200 0 0 30

The issue seems to be with the import api. 

Regards,
Aaron

**Comment by AssafMiron** [comment]
HTTP error 500 with error code 109 is for invalid token
Please see that you have the $LogonHeader parameter initialized with Authorization and that you are using a user that is not connected to any other interface when running this script

**Comment by AssafMiron** [comment]
Hello @cybr-aaronlim ,

Please see #63 that might solve the issue you were experiencing
Please let us know if it solves it

Thanks,
Assaf

**Comment by AssafMiron** [comment]
Hello @simonyzyeh ,

Please see #63  that might solve the issue you were experiencing
Please let us know if it solves it

Thanks,
Assaf

**Comment by simonyzyeh** [comment]
Hello @AssafMiron 
Ok, I'll try it and feedback here

**Comment by simonyzyeh** [comment]
Yes, it's worked with arguments in command line . the message is as below (The connection component has existed in PAS before I ran program)

-----------------------------------------------------------------------------------------
PS C:\Source\epv-api-scripts-master\epv-api-scripts-master\Platforms> .\Import-ConnectionComponents.ps1 -PVWAURL https:
/PAS112/PasswordVault -ConnectionComponentZipPath "SQL Server Mgmt Studio 18-DBAccout.zip" -Verbose
Import Connection Component: Script Started
詳細資訊: POST https://pas112/PasswordVault/api/auth/cyberark/Logon with -1-byte payload
詳細資訊: received 182-byte response of content type application/json; charset=utf-8
詳細資訊: POST https://pas112/PasswordVault/api/ConnectionComponents/Import with -1-byte payload
The requested connection component already exists
Logoff Session...
詳細資訊: POST https://pas112/PasswordVault/api/auth/Logoff with 0-byte payload
詳細資訊: received 16-byte response of content type application/json; charset=utf-8
Import Connection Component: Script Ended
PS C:\Source\epv-api-scripts-master\epv-api-scripts-master\Platforms>

However, if I just run command .\ Import-ConnectionComponents.ps1. 
The script always show that I can not login as following message
----------------------------------------------------------------
Cmdlet Import-ConnectionComponents.ps1 在命令管線位置 1
請提供下列參數的值:
(輸入 !? 可取得說明。)
PVWAURL: https://10.8.8.13/PasswordVault/v10/logon
Import Connection Component: Script Started

Logon Token is Empty - Cannot login

**Comment by AssafMiron** [comment]
Hello @simonyzyeh ,

Please note that in you second run of the script the PVWA URL provided is worng.
You provided:  https://10.8.8.13/PasswordVault/v10/logon
It should be:  https://10.8.8.13/PasswordVault/

If running the script like described above works I will close this issue

Thanks,
Assaf

**Comment by simonyzyeh** [comment]
Oh ! my typo. Sorry about that.
I appreciate your friendly support!
